[package]
name = "oidn"
version = "2.4.1"
edition = "2024"
authors = ["Will Usher <will@willusher.io>"]
build = "build.rs"
homepage = "https://github.com/Twinklebear/oidn-rs"
documentation = "https://docs.rs/oidn"
repository = "https://github.com/Twinklebear/oidn-rs"
readme = "README.md"
license = "MIT"
description = "A wrapper for the Intel OpenImageDenoise image denoising library."
keywords = ["openimagedenoise", "denoise", "denoising"]
include = [
    "/Cargo.toml",
    "/LICENSE.md",
    "/README.md",
    "/build.rs",
    "/src/**",
    "/tests/**",
    "/examples/*.rs",
    "/build-tools/Cargo.toml",
    "/build-tools/src/**",
]
links = "OpenImageDenoise"

[workspace]
members = [".", "xtask", "build-tools"]
default-members = ["."]
resolver = "3"

[features]
default = []
bundled = ["build-tools/bundled"]

[dependencies]
num_enum = "0.7.6"

[build-dependencies]
pkg-config = "0.3.33"
build-tools = { path = "build-tools" }

[dev-dependencies]
rand = "0.10.1"
image = "0.25.10"
exr = "1.74.0"
docopt = "1.1.1"
rayon = "1.12.0"
serde = { version = "1.0.228", features = ["derive"] }
